// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6fBxeadJLF4jBV_NvQ2-RquWuSvKLnw',
    appId: '1:1007371736227:web:0487a8573600ce81dc1b16',
    messagingSenderId: '1007371736227',
    projectId: 'project-y-8df27',
    authDomain: 'project-y-8df27.firebaseapp.com',
    storageBucket: 'project-y-8df27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7DnyW7K6iQdM_mWJRgLW2smlLoXq0WU',
    appId: '1:1007371736227:android:34bee1a9f31f1d3bdc1b16',
    messagingSenderId: '1007371736227',
    projectId: 'project-y-8df27',
    storageBucket: 'project-y-8df27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeY9sdWNctaMJQJ3D-ZDxpCXi7CQ5kZjQ',
    appId: '1:1007371736227:ios:aa60e78a5d6ce794dc1b16',
    messagingSenderId: '1007371736227',
    projectId: 'project-y-8df27',
    storageBucket: 'project-y-8df27.firebasestorage.app',
    iosBundleId: 'com.example.myMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeY9sdWNctaMJQJ3D-ZDxpCXi7CQ5kZjQ',
    appId: '1:1007371736227:ios:aa60e78a5d6ce794dc1b16',
    messagingSenderId: '1007371736227',
    projectId: 'project-y-8df27',
    storageBucket: 'project-y-8df27.firebasestorage.app',
    iosBundleId: 'com.example.myMessengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6fBxeadJLF4jBV_NvQ2-RquWuSvKLnw',
    appId: '1:1007371736227:web:5e99ba3fd9fd033cdc1b16',
    messagingSenderId: '1007371736227',
    projectId: 'project-y-8df27',
    authDomain: 'project-y-8df27.firebaseapp.com',
    storageBucket: 'project-y-8df27.firebasestorage.app',
  );
}
